#!/bin/bash
content=`date`
file="foo.txt"
isAdd=false
while getopts 'f:c:a' OPTION
do
	case $OPTION in
		f) 
			file=$OPTARG
		;;
		a)
			isAdd=true
		;;			
		c)
			content=$OPTARG
		;;
	esac
done
if $isAdd; then
	echo $content >> $file  
else
	echo $content > $file  
fi
git add $file
git commit -m "content $content" 
